# Generated by Django 4.2.1 on 2024-01-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок')),
                ('slug', models.CharField(max_length=100, verbose_name='slug')),
                ('content', models.TextField(max_length=2000, verbose_name='содержимое')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='blog/', verbose_name='превью')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('publication_indicator', models.BooleanField(default=True, verbose_name='признак публикации')),
                ('number_of_view', models.IntegerField(default=0, verbose_name='количество просмотров')),
            ],
        ),
    ]
