# Generated by Django 4.2.1 on 2024-01-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ('title',), 'verbose_name': 'заголовок', 'verbose_name_plural': 'заголовки'},
        ),
    ]
