# Generated by Django 4.2.1 on 2024-01-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='наименование')),
                ('description', models.TextField(max_length=1000, verbose_name='описание')),
                ('preview', models.ImageField(blank=True, null=True, upload_to='product/', verbose_name='превью')),
                ('category', models.CharField(max_length=100, verbose_name='категория')),
                ('price_per_one', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='цена за штуку')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('date_of_change', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
                'ordering': ('name', '-date_of_creation'),
            },
        ),
    ]
